
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeylgwdzknievntcaajd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleWxnd2R6a25pZXZudGNhYWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjMwMTIsImV4cCI6MjA1OTA5OTAxMn0.y-fxO3An72FqEBzndM5F3xevtfkAi_NbEAiINntbzVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
